package org.opendc.simulator.network.policies.routing

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import org.opendc.simulator.network.components.networks.Network
import org.opendc.simulator.network.components.node.Node
import org.opendc.simulator.network.components.node.internals.flowtable.NodeFlowEntry
import org.opendc.simulator.network.flow.internals.INetFlow
import org.opendc.simulator.network.flow.publics.NetFlow
import org.opendc.simulator.network.simscope.NetSimScope
import java.util.Stack

/**
 * **Valiant Random Routing**.
 * To route a packet,
 * the protocol first randomly selects a router Rr different from
 * Rs (sender) and Rd(destination). The packet is then routed along two minimal paths:
 * from Rs to Rr, and from Rr to Rd.
 *
 * Source: https://htor.inf.ethz.ch/publications/img/sf_sc_2014.pdf
 */
@Serializable
@SerialName("val")
internal class VAL: RoutPolicy(), MutableMap<NetFlow, RoutPath> by mutableMapOf() {
    override val internetRoutPolicy: RoutPolicy = this

    context(NetSimScope, Node<*>)
    override suspend fun selectPorts(nodeFlowEntry: NodeFlowEntry) {
        val f = nodeFlowEntry.netFlow
        assert(nodeFlowEntry.txPorts.isEmpty())
        assert(f.destId != this@Node.id)


        // Set ports to forward flow to according to `RoutPath` for flow `f`.
        this[f]!![this@Node]!!.also {
            // With this algorithm (after loops are removed),
            // each node should send each flow to only (exactly) one port.
            assert(it.size == 1)
        }.forEach { port ->
            // Add the port to those to which the flow will be sent to.
            nodeFlowEntry.txPorts += port
        }
    }

    context(NetSimScope)
    override suspend fun onFlowStart(f: INetFlow) {
        this[f] = f.newPath()
    }

    context(NetSimScope)
    override suspend fun onFlowStop(f: INetFlow) {
        assert(this.remove(f) != null)
    }

    context(NetSimScope)
    override suspend fun onNodeAdded(n: Node<*>) {
        TODO()
    }

    context(NetSimScope)
    override suspend fun onNodeRemoved(n: Node<*>) {
        TODO()
    }

    /**
     * @return Random [Node] in [this] [Network], which is not among [excludedNodes].
     */
    private fun Network.randomNodeExcept(vararg excludedNodes: Node<*>): Node<*> {
        var randomIdx = nodeLs.indices.random()
        var n: Node<*>
        do {
            n = nodeLs[randomIdx]
            randomIdx = if (randomIdx == nodeLs.size - 1) 0 else randomIdx + 1
        } while (n in excludedNodes)

        return n
    }

    /**
     * Generates a [RoutPath] for [this]~[INetFlow] according to VAL.
     * The path generated by randomly choosing a middle router Rm is
     * simplified removing the loops that may occur.
     *
     * @return The routing path for the flow.
     */
    context(NetSimScope)
    private suspend fun INetFlow.newPath(): RoutPath {
        val net = this@NetSimScope.net
        val sender = net[senderId]!!
        val dest = net[destId]!!

        // Get random node Rr different from Rs (sender) and Rd (destination).
        val middleRandomN = net.randomNodeExcept(sender, dest, net.internet)

        // Build routing rules for this flow.
        return RoutPath(this@INetFlow) {
            var currN = sender

            // For the first part target is `middleRandomN`,
            // for the second part is the destination node.
            var target = middleRandomN
            while (currN != dest) {
                with(currN) {
                    // Select one of the ports on `currN` that leads
                    // to one of the shortest paths towards `target`.
                    val ports = OSPF.selectPorts(target)
                    assert(ports.size == 1)

                    // Add entry for the current node.
                    put(currN, ports.toMutableSet())

                    // Update `curr` to the node to which the single `Port` in `ports` is connected.
                    currN = ports.first().txLink!!.receiverPort.owner

                    // If `middleRandomN` then the first part of VAL is completed,
                    // and we can proceed to routing from `middleRandomN`
                    // to the actual destination node.
                    if (currN == middleRandomN) target = dest
                }
            }
        }.withNoLoops()
    }

    /**
     * Selecting a random middle router can create loops in the routing path
     * (e.g., simply A->B->C->B->D if C=Rm, A=Rs, D=Rd).
     * This method removes loops
     * (e.g., A->B->C->B->D becomes A->B->D).
     */
    context(NetSimScope)
    private fun RoutPath.withNoLoops(): RoutPath {
        val senderNode: Node<*> = net[this@RoutPath.f.senderId]!!
        val destNode: Node<*> = net[this@RoutPath.f.destId]!!

        // Used to keep track of the nodes in the order they are traversed
        // by the flow and backtrack when loop is detected.
        val stack = Stack<Node<*>>()

        // Backtracks to node `to` removing loop started at `to`.
        fun backTrack(to: Node<*>) {
            // The last node that was removed from the path during back-track.
            var rm: Node<*>? = null
            while (stack.peek() != to) {
                rm = stack.pop()
                this.remove(stack.pop())!!
            }
            // The first node that was part of the loop.
            val n = stack.peek()

            // Remove the step that leaded to loop.
            this[n]!!.remove(n.ports.find { it.txLink!!.receiverPort.owner == rm })
        }

        fun step() {
            // Set of Ports to propagate to.
            this[stack.peek()]
                ?.also {
                    // With the algorithm used in `newPath`, the max
                    // number of ports a flow can be propagated to is 2.
                    assert(it.size <= 2)
                }

                // List of Nodes to propagate to.
                ?.map { p ->
                    p.txLink!!.receiverPort.owner

                // Step in all possible directions (max 2).
                }?.forEach { n ->
                    if (n in stack) return@forEach backTrack(to = n)

                    stack.push(n)
                    step()
                    stack.pop()

                // If no next node is found, the destination node is reached.
                } ?: assert(stack.peek() == destNode)
        }

        stack.push(senderNode)
        step()

        return this@RoutPath
    }
}
