/*
 * Copyright (c) 2024 AtLarge Research
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package org.opendc.simulator.network.flow

import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import org.jetbrains.annotations.VisibleForTesting
import org.opendc.common.units.DataRate
import org.opendc.common.units.DataSize
import org.opendc.common.units.Time
import org.opendc.simulator.network.api.node.NodeId
import org.opendc.simulator.network.components.EndPointNode
import org.opendc.simulator.network.components.stability.NetworkStabilityChecker.Key.getNetStabilityChecker
import org.opendc.simulator.network.utils.ChangeHndlr
import org.opendc.simulator.network.utils.SusChangeHndlr
import java.util.concurrent.ConcurrentHashMap
import kotlin.coroutines.coroutineContext

/**
 * Represents an end-to-end flow, meaning the flow from one [EndPointNode] to another.
 * This end-to-end flow can be split into multiple sub-flows along the path,
 * but ultimately each sub-flow arrives at destination.
 * @param[name]                     name of the flow if any.
 * @param[transmitterId]            id of the [EndPointNode] this end-to-end flow is generated from.
 * @param[destinationId]            id of the [EndPointNode] this end-to-end flow is directed to.
 * @param[demand]                   data rate generated by the sender.
 */
public class NetFlow internal constructor(
    public val name: String = DEFAULT_NAME,
    public val transmitterId: NodeId,
    public val destinationId: NodeId,
    demand: DataRate = DataRate.ZERO,
) {
    public val id: FlowId = runBlocking { nextId() }

    /**
     * Functions [(NetFlow, Kbps, Kbps) -> Unit] invoked whenever the throughput of the flow changes.
     */
    private val throughputSusChangeHndlrs = mutableListOf<SusChangeHndlr<NetFlow, DataRate>>()
    private val throughputChangeHndlrs = mutableListOf<ChangeHndlr<NetFlow, DataRate>>()

    /**
     * Functions [(NetFlow, DataRate, Kbps) -> Unit] invoked whenever the demand of the flow changes.
     */
    private val demandSusChangeHndlrs = mutableListOf<SusChangeHndlr<NetFlow, DataRate>>()
    private val demandChangeHndlrs = mutableListOf<ChangeHndlr<NetFlow, DataRate>>()

    /**
     * Total data transmitted since the start of the flow (in Kb).
     */
    private var totDataTransmitted: DataSize = DataSize.ZERO

    /**
     * The end-to-end throughput of the flow.
     *
     * This property should be updated only by the receiver node
     * coroutine job, hence synchronized update should be guaranteed.
     */
    private var throughput: DataRate = DataRate.ZERO
    private val throughputMtx = Mutex()

    /**
     * The current demand of the flow (in Kbps).
     */
    private var demand: DataRate = demand
    private val demandMtx = Mutex()

    init {
        // Sets up the static destination id retrieval for the flow.
        _flowsDestIds[id] = destinationId
    }

    /**
     * Advances the time for the flow, updating the total data
     * transmitted according to [time] milliseconds timelapse.
     */
    internal suspend fun advanceBy(time: Time) {
        coroutineContext.getNetStabilityChecker().checkIsStableWhile {
            totDataTransmitted += throughput * time
        }
    }

    // //////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    // Demand Getters and Setters
    // //////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    @JvmSynthetic
    public suspend fun setDemand(newDemand: DataRate): Unit =
        demandMtx.withLock {
            val oldDemand = demand
            if (newDemand approx oldDemand) return
            demand = newDemand

            // calls observer handlers
            demandChangeHndlrs.forEach { it.handle(this, oldDemand, newDemand) }
            demandSusChangeHndlrs.forEach { it.handle(this, oldDemand, newDemand) }
        }

    public fun setDemandJava(newDemand: DataRate) {
        runBlocking { setDemand(newDemand) }
    }

    @JvmSynthetic
    internal suspend fun getDemand() = demandMtx.withLock { demand }

    // //////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    // Throughput Getters and Setters
    // //////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    @JvmSynthetic
    internal suspend fun setThroughput(new: DataRate) {
        throughputMtx.withLock {
            if (new == throughput) return
            val old = throughput
            throughput = if (new approx demand) demand else new.roundToIfWithinEpsilon(DataRate.ZERO)

            throughputChangeHndlrs.forEach { it.handle(obj = this, oldValue = old, newValue = throughput) }
            throughputSusChangeHndlrs.forEach { it.handle(this, oldValue = old, newValue = throughput) }
        }
    }

    @JvmSynthetic
    public suspend fun getThroughput(): DataRate = throughputMtx.withLock { throughput }

    @JvmSynthetic
    public suspend fun increaseThroughputBy(amount: DataRate) {
        throughputMtx.withLock {
            val old: DataRate = throughput
            throughput += amount
            throughputSusChangeHndlrs.forEach { it.handle(this, old, throughput) }
            throughputChangeHndlrs.forEach { it.handle(this, old, throughput) }
        }
    }

    public fun getThroughputJava(): DataRate =
        runBlocking {
            throughputMtx.withLock { throughput }
        }

    // //////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    // Observers
    // //////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    /**
     * Adds [hndlr] among the functions invoked whenever the throughput of the flow changes.
     */
    public fun withThroughputSusChangeHndlr(hndlr: SusChangeHndlr<NetFlow, DataRate>): NetFlow {
        throughputSusChangeHndlrs.add(hndlr)
        return this
    }

    /**
     * @see withThroughputSusChangeHndlr
     */
    public fun withThroughputChangeHndlr(hndlr: ChangeHndlr<NetFlow, DataRate>): NetFlow {
        throughputChangeHndlrs.add(hndlr)
        return this
    }

    /**
     * Adds [f] among the functions invoked whenever the demand of the flow changes.
     */
    internal fun withDemandChangeHndlr(f: SusChangeHndlr<NetFlow, DataRate>): NetFlow {
        demandSusChangeHndlrs.add(f)
        return this
    }

    /**
     * Adds [f] among the functions invoked whenever the demand of the flow changes.
     */
    internal fun withDemandChangeHndlrJava(f: ChangeHndlr<NetFlow, DataRate>): NetFlow {
        demandChangeHndlrs.add(f)
        return this
    }

    // //////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    // Other
    // //////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    override fun toString(): String =
        "NetFlow(id=$id, name=$name, transmitterId=$transmitterId, destinationId=$destinationId, currentDemand=$demand)"

    /**
     * Invoked by the garbage collector whenever a flow is destroyed.
     * It is deprecated since it does not offer any guarantees to be invoked,
     * but guarantees in these case are not needed, removing some entries
     * is only for slightly improved performances.
     */
    @Suppress("removal")
    protected fun finalize() {
        _flowsDestIds.remove(this.id)
    }

    internal companion object {
        internal const val DEFAULT_NAME: String = "unknown"

        @VisibleForTesting
        internal fun reset() {
            nextId = 0
            _flowsDestIds.clear()
        }

        /**
         * Returns a unique flow id [Long].
         */
        private var nextId: FlowId = 0
        private val nextIdLock = Mutex()

        suspend fun nextId(): FlowId =
            nextIdLock.withLock {
                if (nextId == FlowId.MAX_VALUE) throw RuntimeException("flow id reached its maximum value")
                nextId++
                nextId - 1
            }

        /**
         * Stores the [NodeId] of the destination for each [NetFlow]
         * not yet discarded by the garbage collector.
         */
        internal val flowsDestIds: Map<FlowId, NodeId> get() = _flowsDestIds
        private val _flowsDestIds = ConcurrentHashMap<FlowId, NodeId>()
    }
}

/**
 * Type alias for improved understandability.
 */
public typealias FlowId = Long
