/*
 * Copyright (c) 2024 AtLarge Research
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package org.opendc.simulator.network.api

import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import org.jetbrains.annotations.VisibleForTesting
import org.opendc.common.annotations.InternalUse
import org.opendc.common.units.DataRate
import org.opendc.common.units.DataSize
import org.opendc.common.units.TimeDelta
import org.opendc.simulator.network.api.node.NodeId
import org.opendc.simulator.network.components.EndPointNode
import org.opendc.simulator.network.components.stability.NetworkStabilityChecker.Key.getNetStabilityChecker
import org.opendc.simulator.network.utils.ChangeHndlr
import org.opendc.simulator.network.utils.SusChangeHndlr
import org.opendc.simulator.network.utils.observable.DelegatedObservable
import org.opendc.simulator.network.utils.observable.HndlrsLs
import org.opendc.simulator.network.utils.observable.Observable
import org.opendc.simulator.network.utils.observable.ObservableProperty
import org.opendc.simulator.network.utils.withTransferredLock
import java.util.concurrent.ConcurrentHashMap
import kotlin.coroutines.CoroutineContext
import kotlin.coroutines.coroutineContext

/**
 * Represents an end-to-end flow, meaning the flow from one [EndPointNode] to another.
 * This end-to-end flow can be split into multiple sub-flows along the path,
 * but ultimately each sub-flow arrives at destination.
 *
 * Event handlers are guaranteed to be executed in order.
 * However, this class does not guarantee that when the handlers are executed, the state hasn't changed in the meantime.
 *
 * @param[name]                     name of the flow if any.
 * @param[transmitterId]            id of the [EndPointNode] this end-to-end flow is generated from.
 * @param[destinationId]            id of the [EndPointNode] this end-to-end flow is directed to.
 * @param[demand]                   data rate generated by the sender.
 */
public class NetFlow internal constructor(
    public val name: String = DEFAULT_NAME,
    public val transmitterId: NodeId,
    public val destinationId: NodeId,
    demand: DataRate = DataRate.zero,
): Observable<NetFlow> by DelegatedObservable() {
    public val id: FlowId = runBlocking { nextId() }

//    /**
//     * Functions invoked whenever the throughput of the flow changes.
//     */
//    private val throughputHndlrs = HndlrsLs<NetFlow, DataRate>()
//
//    /**
//     * Functions invoked whenever the demand of the flow changes.
//     */
//    private val demandHndlrs = HndlrsLs<NetFlow, DataRate>()
//
//    /**
//     * Functions invoked whenever the [fragmentTarget] is reached.
//     */
//    private val fragmentCompletionHndlrs = HndlrsLs<NetFlow, DataSize>()
    private var fragmentCompletionHandled = false
//
//    /**
//     * To ensure that handlers are invoked in the correct order.
//     */
//    private val hndlrsMtx = Mutex()
//
//    /**
//     * To ensure handlers lists
//     */
//    private val hndlrsLsMtx = Mutex()

    /**
     * Total data transmitted since the start of the flow (in Kb).
     */
    public var totDataTransmitted: DataSize = DataSize.zero
        private set

    /**
     * Total data transmitted when the fragment started.
     */
    private var fragmentStart: DataSize = DataSize.zero

    /**
     * Data to be transmitted in this fragment. If target never set, fragments are never used.
     */
    public var fragmentTarget: DataSize = DataSize.max
        private set

    /**
     * The end-to-end throughput of the flow.
     *
     * This property should be updated only by the receiver node
     * coroutine job.
     */
    private var throughput: DataRate = DataRate.zero
    private val throughputMtx = Mutex()

    /**
     * The current demand of the flow.
     */
    private var demand: DataRate = demand
    private val demandMtx = Mutex()

    init {
        // Sets up the static destination id retrieval for the flow.
        _flowsDestIds[id] = destinationId
    }

    /**
     * Advances the time for the flow, updating the total data
     * transmitted according to [time] milliseconds timelapse.
     */
    @OptIn(InternalUse::class)
    internal suspend fun advanceBy(
        time: TimeDelta,
        checkStability: Boolean = false,
    ) {
        suspend fun doAdvance() {
            throughputMtx.withTransferredLockHndlChange(FRAGMENT_COMPLETION) hndlr@ {
                totDataTransmitted += throughput * time
                if (fragmentCompletionHandled || totDataTransmitted approxSmaller  fragmentTarget) return@hndlr null
                fragmentCompletionHandled = true
                Observable.OldNewPair(fragmentStart, fragmentTarget)
            }
//            throughputMtx.withTransferredLock(hndlrsMtx, {
//                totDataTransmitted += throughput * time
//                fragmentCompletionHandled.not() && totDataTransmitted approxLargerOrEq fragmentTarget
//            }) {
//                totDataTransmitted = fragmentTarget
//                fragmentCompletionHndlrs.handleAll(this, fragmentStart, fragmentTarget)
//                fragmentCompletionHandled = true
//            }
        }

        if (checkStability) {
            coroutineContext.getNetStabilityChecker().checkIsStableWhile { doAdvance() }
        } else {
            doAdvance()
        }
    }

    // //////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    // Fragment Functionality
    // //////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    /**
     * Saves how much data was transmitted through this flow at this point in time, and starts a new fragment.
     * @param target the target data to be transmitted in this fragment.
     *
     * This function is not thread safe, it is assumed to be invoked sequentially.
     */
    @JvmSynthetic
    public fun newFragment(target: DataSize) {
        fragmentStart = totDataTransmitted
        fragmentTarget = target
        fragmentCompletionHandled = false
    }

    /**
     * @see newFragment
     */
    public fun newFragmentJava(target: Double): Unit = newFragment(DataSize.ofKib(target))

    /**
     * @return The amount of data transmitted by this flow since the last call to [newFragment].
     */
    @JvmSynthetic
    public suspend fun transmittedInFragment(): DataSize = throughputMtx.withLock { totDataTransmitted - fragmentStart }

    /**
     * @see transmittedInFragment
     */
    public fun transmittedInFragmentJava(): DataSize = runBlocking { transmittedInFragment() }

    // //////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    // Demand Getters and Setters
    // //////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    @OptIn(InternalUse::class)
    @JvmSynthetic
    public suspend fun setDemand(newDemand: DataRate): Unit =
        demandMtx.withTransferredLockHndlChange(DEMAND) hndlr@ {
            val oldDemand = demand
            if (newDemand approx oldDemand) return@hndlr null
            demand = newDemand
            Observable.OldNewPair(oldDemand, demand)
        }
//        demandMtx.withLock {
//            val oldDemand = demand
//            if (newDemand approx oldDemand) return
//            demand = newDemand
//
//            // calls observer handlers
//            demandHndlrs.handleAll(this, oldDemand, newDemand)
//        }

    public fun setDemandJava(newDemand: Double) {
        runBlocking { setDemand(DataRate.ofKbps(newDemand)) }
    }

    @JvmSynthetic
    public suspend fun getDemand(): DataRate = demandMtx.withLock { demand }

    public fun getDemandJava(): DataRate = runBlocking { getDemand() }

    // //////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    // Throughput Getters and Setters
    // //////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    /**
     * Should be invoked only internally by the coroutine that handles the update at the destination node.
     */
    @OptIn(InternalUse::class)
    @JvmSynthetic
    internal suspend fun setThroughput(new: DataRate) =
        throughputMtx.withTransferredLockHndlChange(THROUGHPUT) hndlr@ {
            if (new == throughput) return@hndlr null
            val old = throughput
            throughput = if (new approx demand) demand else new.roundToIfWithinEpsilon(DataRate.zero)
            Observable.OldNewPair(old, new)
        }
//        var old: DataRate = DataRate.zero
//        throughputMtx.withTransferredLock(hndlrsMtx, {
//            if (new == throughput) return
//            old = throughput
//            throughput = if (new approx demand) demand else new.roundToIfWithinEpsilon(DataRate.zero)
//            true // Transfer lock to second mutex and execute second lambda.
//        }) {
//            throughputHndlrs.handleAll(this, old, new)
//        }
//    }

    @JvmSynthetic
    public suspend fun getThroughput(): DataRate =
        throughputMtx.withLock(coroutineContext) {
            throughput
        }

    @OptIn(InternalUse::class)
    @JvmSynthetic
    public suspend fun increaseThroughputBy(amount: DataRate) {
        if (amount == DataRate.zero) return
        throughputMtx.withTransferredLockHndlChange(THROUGHPUT) hndlr@{
            val old = throughput
            throughput += amount
            Observable.OldNewPair(old, throughput)
        }
    }
//        if (amount.isZero()) return
//        var old: DataRate = DataRate.zero
//        throughputMtx.withTransferredLock(hndlrsMtx, {
//            old = throughput
//            throughput += amount
//            true // Transfer lock to second mutex and execute second lambda.
//        }) {
//            throughputHndlrs.handleAll(this, old, throughput)
//        }
//    }

    public fun getThroughputJava(): DataRate =
        runBlocking {
            getThroughput()
        }

    // //////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    // Observers
    // //////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//    /**
//     * Adds [hndlr] among the functions invoked whenever the throughput of the flow changes.
//     */
//    public fun withThroughputChangeHndlr(hndlr: SusChangeHndlr<NetFlow, DataRate>): NetFlow {
//        throughputHndlrs.addSus(hndlr)
//        return this
//    }
//
//    /**
//     * Adds [hndlr] among the callbacks that are queued, when [throughput] changes,
//     * in the network [CoroutineContext] to be invoked sequentially in the future.
//     *
//     * @see org.opendc.simulator.network.api.integration.SeqComputeIntegration
//     */
//    public fun withThroughputChangeHndlrSeq(hndlr: ChangeHndlr<NetFlow, DataRate>): NetFlow {
//        throughputHndlrs.addSeq(hndlr)
//        return this
//    }
//
//    /**
//     * Adds [hndlr] among the functions invoked whenever the demand of the flow changes.
//     */
//    internal fun withDemandChangeHndlr(hndlr: SusChangeHndlr<NetFlow, DataRate>): NetFlow {
//        demandHndlrs.addSus(hndlr)
//        return this
//    }
//
//    /**
//     * Adds [hndlr] among the callbacks that are queued, when the [demand] changes,
//     * in the network [CoroutineContext] to be invoked sequentially in the future.
//     *
//     * @see org.opendc.simulator.network.api.integration.SeqComputeIntegration
//     */
//    internal fun withDemandChangeHndlrSeq(hndlr: ChangeHndlr<NetFlow, DataRate>): NetFlow {
//        demandHndlrs.addSeq(hndlr)
//        return this
//    }
//
//    /**
//     * Adds [f] among the functions invoked whenever the [fragmentTarget] is reached.
//     */
//    public fun withFragmentCompletionHndlr(f: SusChangeHndlr<NetFlow, DataSize>): NetFlow {
//        fragmentCompletionHndlrs.addSus(f)
//        return this
//    }
//
//    /**
//     * Adds [hndlr] among the callbacks that are queued, when the [fragmentTarget] is reached,
//     * in the network [CoroutineContext] to be invoked sequentially in the future.
//     *
//     * @see org.opendc.simulator.network.api.integration.SeqComputeIntegration
//     */
//    public fun withFragmentCompletionHndlrJava(hndlr: ChangeHndlr<NetFlow, DataSize>): NetFlow {
//        fragmentCompletionHndlrs.addSeq(hndlr)
//        return this
//    }

    // //////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    // Other
    // //////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    override fun toString(): String =
        "NetFlow(id=$id, name=$name, transmitterId=$transmitterId, " +
            "destinationId=$destinationId, demand=$demand, throughput=$throughput)"

    /**
     * Invoked by the garbage collector whenever a flow is destroyed.
     */
    @Suppress("removal")
    protected fun finalize() {
        _flowsDestIds.remove(this.id)
    }

    // //////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    // Companion
    // //////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    public companion object {
        // //////////////////////////////////////////////////////////////////////////////////////////////////////////////
        // Observable Properties
        // //////////////////////////////////////////////////////////////////////////////////////////////////////////////

        public val DEMAND: ObservableProperty<NetFlow, DataRate> = ObservableProperty()
        public val THROUGHPUT: ObservableProperty<NetFlow, DataRate> = ObservableProperty()
        public val FRAGMENT_COMPLETION: ObservableProperty<NetFlow, DataSize> = ObservableProperty()



        internal const val DEFAULT_NAME: String = "unknown"

        @VisibleForTesting
        internal fun reset() {
            nextId = 0
            _flowsDestIds.clear()
        }

        private var nextId: FlowId = 0
        private val nextIdLock = Mutex()

        /**
         * Returns a unique flow id [Long].
         */
        internal suspend fun nextId(): FlowId =
            nextIdLock.withLock {
                if (nextId == FlowId.MAX_VALUE) throw RuntimeException("flow id reached its maximum value")
                nextId++
                nextId - 1
            }

        /**
         * Stores the [NodeId] of the destination for each [NetFlow]
         * not yet discarded by the garbage collector.
         */
        internal val flowsDestIds: Map<FlowId, NodeId> get() = _flowsDestIds
        private val _flowsDestIds = ConcurrentHashMap<FlowId, NodeId>()
    }
}

/**
 * Type alias for improved understandability.
 */
public typealias FlowId = Long
