/*
 * Copyright (c) 2024 AtLarge Research
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package org.opendc.simulator.network.api

import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import org.jetbrains.annotations.VisibleForTesting
import org.opendc.common.annotations.InternalUse
import org.opendc.common.units.DataRate
import org.opendc.common.units.DataSize
import org.opendc.common.units.TimeDelta
import org.opendc.simulator.network.api.node.NodeId
import org.opendc.simulator.network.components.EndPointNode
import org.opendc.simulator.network.components.stability.NetworkStabilityChecker.Key.getNetStabilityChecker
import org.opendc.simulator.network.utils.observable.DelegatedObservable
import org.opendc.simulator.network.utils.observable.Observable
import org.opendc.simulator.network.utils.observable.elements.ObservableEvent
import org.opendc.simulator.network.utils.observable.elements.ObservableProperty
import java.util.concurrent.ConcurrentHashMap
import kotlin.coroutines.coroutineContext

/**
 * Represents an end-to-end flow, meaning the flow from one [EndPointNode] to another.
 * This end-to-end flow can be split into multiple sub-flows along the path,
 * but ultimately each sub-flow arrives at destination.
 *
 * Event handlers are guaranteed to be executed in order.
 * However, this class does not guarantee that when the handlers are executed, the state hasn't changed in the meantime.
 *
 * @param[name]                     name of the flow if any.
 * @param[transmitterId]            id of the [EndPointNode] this end-to-end flow is generated from.
 * @param[destinationId]            id of the [EndPointNode] this end-to-end flow is directed to.
 * @param[demand]                   data rate generated by the sender.
 */
public class NetFlow internal constructor(
    public val name: String = DEFAULT_NAME,
    public val transmitterId: NodeId,
    public val destinationId: NodeId,
    demand: DataRate = DataRate.zero,
) : Observable<NetFlow> by DelegatedObservable() {
    public val id: FlowId = runBlocking { nextId() }

    @Volatile
    public var fragmentIdx: Long = 0

    private var fragmentCompletionHandled = true

    /**
     * Total data transmitted since the start of the flow (in Kb).
     */
    public var totDataTransmitted: DataSize = DataSize.zero
        private set

    /**
     * Total data transmitted when the fragment started.
     */
    public var fragmentStart: DataSize = DataSize.zero
        private set

    /**
     * Data to be transmitted in this fragment. If target never set, fragments are never used.
     */
    public var fragmentTarget: DataSize = DataSize.zero
        private set

    /**
     * The end-to-end throughput of the flow.
     *
     * This property should be updated only by the receiver node
     * coroutine job.
     */
    private var throughput: DataRate = DataRate.zero
    private val throughputLock = Mutex()

    /**
     * The current demand of the flow.
     */
    private var demand: DataRate = demand
    private val demandLock = Mutex()

    init {
        @OptIn(InternalUse::class)
        setUpDelegatedObservable(this)
        // Sets up the static destination id retrieval for the flow.
        _flowsDestIds[id] = destinationId
    }

    /**
     * Advances the time for the flow, updating the total data
     * transmitted according to [time] milliseconds timelapse.
     */
    @OptIn(InternalUse::class)
    internal suspend fun advanceBy(
        time: TimeDelta,
        checkStability: Boolean = false,
    ) {
        suspend fun doAdvance() {
            var toHandle = false
            throughputLock.withLock {
                totDataTransmitted += throughput * time
                if (fragmentCompletionHandled || totDataTransmitted approxSmaller (fragmentTarget + fragmentStart)) return@withLock
                totDataTransmitted = fragmentTarget + fragmentStart
                fragmentCompletionHandled = true
                toHandle = true
            }
            if (toHandle) triggerHandlers(FRAGMENT_COMPLETION)
        }

        if (checkStability) {
            coroutineContext.getNetStabilityChecker().checkIsStableWhile { doAdvance() }
        } else {
            doAdvance()
        }
    }

    // //////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    // Fragment Functionality
    // //////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    /**
     * Saves how much data was transmitted through this flow at this point in time, and starts a new fragment.
     * @param target the target data to be transmitted in this fragment.
     *
     * This function is not thread safe, it is assumed to be invoked sequentially.
     */
    @OptIn(InternalUse::class)
    @JvmSynthetic
    public fun newFragment(target: DataSize) {
        fragmentIdx++
        fragmentStart = totDataTransmitted
        fragmentTarget = target
        if (target > DataSize.zero) {
            fragmentCompletionHandled = false
        } else {
            fragmentCompletionHandled = true
            runBlocking { triggerHandlers(FRAGMENT_COMPLETION) }
        }
    }

    /**
     * @see newFragment
     */
    public fun newFragmentJava(target: Double): Unit = newFragment(DataSize.ofKb(target))

    /**
     * @return The amount of data transmitted by this flow since the last call to [newFragment].
     */
    public fun transmittedInFragment(): DataSize = totDataTransmitted - fragmentStart


    // //////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    // Demand Getters and Setters
    // //////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    @OptIn(InternalUse::class)
    @JvmSynthetic
    public suspend fun setDemand(newDemand: DataRate) {
        var oldDemand: DataRate
        demandLock.withLock {
            oldDemand = demand
            if (newDemand approx oldDemand) return
            demand = newDemand
        }
        triggerHandlers(DEMAND, oldDemand, newDemand)
    }

    public fun setDemandJava(newDemand: Double) {
        runBlocking { setDemand(DataRate.ofKbps(newDemand)) }
    }

    @JvmSynthetic
    public suspend fun getDemand(): DataRate = demandLock.withLock { demand }

    public fun getDemandJava(): DataRate = runBlocking { getDemand() }

    // //////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    // Throughput Getters and Setters
    // //////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    /**
     * Should be invoked only internally by the coroutine that handles the update at the destination node.
     */
    @OptIn(InternalUse::class)
    @JvmSynthetic
    internal suspend fun setThroughput(new: DataRate) {
        @Suppress("NAME_SHADOWING") val new: DataRate = new max DataRate.zero
        var old: DataRate
        throughputLock.withLock {
            if (new == throughput) return
            old = throughput
            throughput = if (new approx demand) demand else new.roundToIfWithinEpsilon(DataRate.zero)
        }
        triggerHandlers(THROUGHPUT, old, new)
    }

    @JvmSynthetic
    public suspend fun getThroughput(): DataRate =
        throughputLock.withLock {
            throughput
        }

    @OptIn(InternalUse::class)
    @JvmSynthetic
    public suspend fun increaseThroughputBy(amount: DataRate) {
        if (amount == DataRate.zero) return
        var old: DataRate
        throughputLock.withLock {
            old = throughput
            throughput = (throughput + amount).roundToIfWithinEpsilon(DataRate.zero)
        }
        triggerHandlers(THROUGHPUT, old, throughput)
    }

    public fun getThroughputJava(): DataRate =
        runBlocking {
            getThroughput()
        }

    // //////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    // Other
    // //////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    override fun toString(): String =
        "NetFlow(id=$id, name=$name, transmitterId=$transmitterId, " +
            "destinationId=$destinationId, demand=$demand, throughput=$throughput)"

    /**
     * Invoked by the garbage collector whenever a flow is destroyed.
     */
    @Suppress("removal")
    protected fun finalize() {
        _flowsDestIds.remove(this.id)
    }

    // //////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    // Companion
    // //////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    public companion object {
        // //////////////////////////////////////////////////////////////////////////////////////////////////////////////
        // Observable Properties
        // //////////////////////////////////////////////////////////////////////////////////////////////////////////////

        public val DEMAND: ObservableProperty<NetFlow, DataRate> = ObservableProperty()
        public val THROUGHPUT: ObservableProperty<NetFlow, DataRate> = ObservableProperty()
        public val FRAGMENT_COMPLETION: ObservableEvent<NetFlow> = ObservableEvent()

        internal const val DEFAULT_NAME: String = "unknown"

        @VisibleForTesting
        internal fun reset() {
            nextId = 0
            _flowsDestIds.clear()
        }

        private var nextId: FlowId = 0
        private val nextIdLock = Mutex()

        /**
         * Returns a unique flow id [Long].
         */
        internal suspend fun nextId(): FlowId =
            nextIdLock.withLock {
                if (nextId == FlowId.MAX_VALUE) throw RuntimeException("flow id reached its maximum value")
                nextId++
                nextId - 1
            }

        /**
         * Stores the [NodeId] of the destination for each [NetFlow]
         * not yet discarded by the garbage collector.
         */
        internal val flowsDestIds: Map<FlowId, NodeId> get() = _flowsDestIds
        private val _flowsDestIds = ConcurrentHashMap<FlowId, NodeId>()
    }
}

/**
 * Type alias for improved understandability.
 */
public typealias FlowId = Long
